### PR TITLE
CAP-340 Update clean air framework to use the EDR meta implementation for its metadata storage

### PR DESCRIPTION
**Pull request by crbunney**

### CODE REVIEW

**Comment by crbunney** [comment]
@tomw66, @corinnebosley, now that various other PRs have been merged, the tests are passing and this is (finally) ready for review! :metal:

**Review by corinnebosley — APPROVED** [review]
@crbunney Nice work. Very meta, one might say.  

I'm assuming that the tests removed in this PR are covered in the edr_server repo, and that there is a good reason for changing some of the metadata functions here to serialise to json rather than yaml.

If all that's true then it all looks good to me.

**Comment by crbunney** [comment]
Thanks :)

> I'm assuming that the tests removed in this PR are covered in the edr_server repo, and that there is a good reason for changing some of the metadata functions here to serialise to json rather than yaml.

That's right, the removed tests & code were duplicates of what exists within `edr_server`, consolidating them in this way means we only need to maintain a single copy (until such time that we need them to diverge)

The switch from yaml to JSON was because `edr_server` already provides JSON serialisation, and there was no advantage to maintaining two different serialisation formats (and increased maintenance overhead is a clear disadvantage)

**Comment by corinnebosley** [comment]
🎉Yayy!

**Pull request merged**
